name: game
description: Space game

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^1.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2

flutter:
  uses-material-design: true
